### ISSUE TITLE
Arc::make_mut clones data instead of making reference

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Brooooooklyn/rolldown#26]
Note in the graph.rs, where probably the `module` wants a reference to `graph`.

https://github.com/Brooooooklyn/rolldown/blob/main/packages/core/src/graph.rs#L60-L61

But actually `ret` and `ret_clone` points to two different value.

Accroding to  https://doc.rust-lang.org/std/sync/struct.Arc.html#method.make_mut

> Makes a mutable reference into the given Arc.
>
> If there are other Arc or Weak pointers to the same allocation, then make_mut will create a new allocation and invoke clone on the inner value to ensure unique ownership. This is also referred to as clone-on-write.

It might be a bug but I'm not sure.

**Comment by Brooooooklyn** [comment]
You are right, `Arc` here is not working as expected, I'll fix it.
